/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/896022da-d0a0-462c-8110-bfa1830b97a3 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool fan;
  bool led;
  bool tulelight;
  bool tv;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
int d1=15;
int d2=2;
int d3=4;
int d4=5;

int sw1=32;
int sw2=33;
int sw3=34;
int sw4=35;

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  pinMode(d1,OUTPUT);
  pinMode(d2,OUTPUT);
  pinMode(d3,OUTPUT);
  pinMode(d4,OUTPUT);
  
  pinMode(sw1,INPUT);
  pinMode(sw2,INPUT);
  pinMode(sw3,INPUT);
  pinMode(sw4,INPUT);
  
  tv=false;
  tulelight=false;
  led=false;
  fan=false;
  
  
  digitalWrite(d1,!tv);
  digitalWrite(d2,!tulelight);
  digitalWrite(d3,!led);
  digitalWrite(d4,!fan);
  

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  
  ArduinoCloud.update();
  
  // Your code here 
  // if(digitalRead(sw1)==tv)
  // tv=!tv;
  
  // if(digitalRead(sw2)==tubelight)
  // tubelight=!tubelight;
  
  // if(digitalRead(sw3)==led)
  // led=!led;
  
  // if(digitalRead(sw4)==fan)
  // fan=!fan;
  
  
  
  
}


/*
  Since Tv is READ_WRITE variable, onTvChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTvChange()  {
  // Add your code here to act upon Tv change
  digitalWrite(d1,!tv);
}

/*
  Since Tulelight is READ_WRITE variable, onTulelightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTulelightChange()  {
  // Add your code here to act upon Tulelight change
  digitalWrite(d2,!tulelight);
}

/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon Led change
  digitalWrite(d3,!led);
}

/*
  Since Fan is READ_WRITE variable, onFanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFanChange()  {
  // Add your code here to act upon Fan change
  digitalWrite(d4,!fan);
}

